version: 2.1

orbs:
  slack: circleci/slack@4.4.2
  aws-cli: circleci/aws-cli@2.0.3
#  ------------------------------------------------------------------------------------------------------------------------------------------
#  defaults (like global variables dubstiuted below)
#  ------------------------------------------------------------------------------------------------------------------------------------------
docvarnode: &dok_node
    docker:
      - image: circleci/node:13.8.0

docvaraws: &dok_awscli
    docker:
      - image: amazon/aws-cli    

docansibl: &dok_ansible
    docker:
      - image: python:3.7-alpine3.11 

slackvarfail: &slack_msg      
          event: fail
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [{"type": "plain_text",
                      "text": "Udapeople build STEP : ${MY_STEP_NAME} Failure #<< pipeline.number >> for << pipeline.project.git_url >> / << pipeline.git.branch >> ",
                      "emoji": true }]
                }
              ]
            } 
#  ------------------------------------------------------------------------------------------------------------------------------------------
#  list of commands used in job 
#
#  ------------------------------------------------------------------------------------------------------------------------------------------

commands:
# ----------------------------------   to destroy the aws infra ----------------------------------------------------------------------------
  destroy-environment:
    description: test the destroy environment
    steps:
      - run:
          name: Destroy environments          
          command: |
            apt-get install -y python3-pip
            pip install awscli
            aws --version

# ----------------------------------   to reverse the migration   --------------------------------------------------------------------------
  revert-migrations:
    description: Revert migration test
    steps:
      - run:
          name: Revert migrations          
          command: |
              apt-get install nodejs -y
              npm --version
#  ------------------------------------------------------------------------------------------------------------------------------------------
#    Jobs list startd from here    
#
#
#  ------------------------------------------------------------------------------------------------------------------------------------------
jobs:
  test-cmds:
    <<: *dok_ansible                 
    steps:
      - checkout
      - destroy-environment         
      - revert-migrations
      - slack/notify:
          <<: *slack_msg
# -------------------------------------------------------------------------------
#
#         WORKFLOW  STEPS STARTS FROM HERE
#
# -------------------------------------------------------------------------------
workflows:
  default:
    jobs:
      - test-cmds
